set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
  BYTEDECK_TRIMUI_TOOLCHAIN_PREFIX
  BYTEDECK_TRIMUI_SYSROOT
)

set(BYTEDECK_TRIMUI_TOOLCHAIN_PREFIX "" CACHE STRING "Compiler prefix, for example /opt/toolchains/bin/aarch64-linux-gnu-")
set(BYTEDECK_TRIMUI_SYSROOT "" CACHE PATH "Optional sysroot for TrimUI cross-builds")

if(NOT BYTEDECK_TRIMUI_TOOLCHAIN_PREFIX AND DEFINED ENV{BYTEDECK_TRIMUI_TOOLCHAIN_PREFIX})
  set(BYTEDECK_TRIMUI_TOOLCHAIN_PREFIX "$ENV{BYTEDECK_TRIMUI_TOOLCHAIN_PREFIX}" CACHE STRING "" FORCE)
endif()

if(NOT BYTEDECK_TRIMUI_SYSROOT AND DEFINED ENV{BYTEDECK_TRIMUI_SYSROOT})
  set(BYTEDECK_TRIMUI_SYSROOT "$ENV{BYTEDECK_TRIMUI_SYSROOT}" CACHE PATH "" FORCE)
endif()

if(NOT BYTEDECK_TRIMUI_TOOLCHAIN_PREFIX)
  message(FATAL_ERROR "BYTEDECK_TRIMUI_TOOLCHAIN_PREFIX is required for TrimUI builds")
endif()

set(CMAKE_C_COMPILER "${BYTEDECK_TRIMUI_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${BYTEDECK_TRIMUI_TOOLCHAIN_PREFIX}g++")

if(BYTEDECK_TRIMUI_SYSROOT)
  set(CMAKE_SYSROOT "${BYTEDECK_TRIMUI_SYSROOT}")
  set(CMAKE_FIND_ROOT_PATH "${BYTEDECK_TRIMUI_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
